export const DEFAULT_COMPUTED_PROPERTIES = [
  "display",
  "position",
  "z-index",
  "opacity",
  "visibility",
  "color",
  "background-color",
  "font-family",
  "font-size",
  "font-weight",
  "line-height",
  "letter-spacing",
  "text-align",
  "white-space",
  "margin-top",
  "margin-right",
  "margin-bottom",
  "margin-left",
  "padding-top",
  "padding-right",
  "padding-bottom",
  "padding-left",
  "border-top-width",
  "border-right-width",
  "border-bottom-width",
  "border-left-width",
  "border-top-style",
  "border-right-style",
  "border-bottom-style",
  "border-left-style",
  "border-top-color",
  "border-right-color",
  "border-bottom-color",
  "border-left-color",
  "width",
  "height",
  "min-width",
  "max-width",
  "min-height",
  "max-height",
  "overflow-x",
  "overflow-y",
] as const;

export const DEFAULT_INHERITED_PROPERTIES = [
  "color",
  "font",
  "font-family",
  "font-size",
  "font-style",
  "font-weight",
  "font-stretch",
  "font-variant",
  "font-feature-settings",
  "font-kerning",
  "line-height",
  "letter-spacing",
  "word-spacing",
  "text-align",
  "text-indent",
  "text-transform",
  "text-decoration-color",
  "text-decoration-line",
  "text-decoration-style",
  "white-space",
  "visibility",
  "cursor",
  "direction",
  "unicode-bidi",
  "list-style-type",
  "list-style-position",
  "list-style-image",
  "quotes",
] as const;

export function inheritedPropertySet(extra: string[] = []): Set<string> {
  return new Set<string>([...DEFAULT_INHERITED_PROPERTIES, ...extra]);
}
